import { WordPair } from './types';

export const WORD_LIST: WordPair[] = [
  // 896 〜 915 相当 (image_85aa5a.jpg 左列)
  { id: 1, jp: "特別な", en: "special", reading: "スペシャル" },
  { id: 2, jp: "特に", en: "especially", reading: "エスペシャリー" },
  { id: 3, jp: "〜以外は", en: "except", reading: "エクセプト" },
  { id: 4, jp: "受け入れる", en: "accept", reading: "アクセプト" },
  { id: 5, jp: "交換する", en: "exchange", reading: "エクスチェンジ" },
  { id: 6, jp: "貸す", en: "lend", reading: "レンド" },
  { id: 7, jp: "借りる", en: "borrow", reading: "ボロウ" },
  { id: 8, jp: "申し出", en: "offer", reading: "オファー" },
  { id: 9, jp: "供給", en: "supply", reading: "サプライ" },
  { id: 10, jp: "公共の", en: "public", reading: "パブリック" },
  { id: 11, jp: "個人的な", en: "private", reading: "プライベート" },
  { id: 12, jp: "社会の", en: "social", reading: "ソーシャル" },
  { id: 13, jp: "個人の", en: "individual", reading: "インディビジュアル" },
  { id: 14, jp: "理由", en: "reason", reading: "リーズン" },
  { id: 15, jp: "意見", en: "opinion", reading: "オピニオン" },
  { id: 16, jp: "推測する", en: "guess", reading: "ゲス" },
  { id: 17, jp: "だと思う", en: "suppose", reading: "サポーズ" },
  { id: 18, jp: "予期する", en: "expect", reading: "エクスペクト" },
  { id: 19, jp: "行う", en: "take", reading: "テイク" },
  { id: 20, jp: "ふるまう", en: "behave", reading: "ビヘイブ" },

  // 916 〜 931 相当 (image_85aa5a.jpg 右列)
  { id: 21, jp: "祝う", en: "celebrate", reading: "セレブレイト" },
  { id: 22, jp: "方法", en: "method", reading: "メソッド" },
  { id: 23, jp: "見える", en: "appear", reading: "アピア" },
  { id: 24, jp: "存在する", en: "exist", reading: "イグジスト" },
  { id: 25, jp: "きれいな", en: "clean", reading: "クリーン" },
  { id: 26, jp: "汚い", en: "dirty", reading: "ダーティ" },
  { id: 27, jp: "質", en: "quality", reading: "クオリティ" },
  { id: 28, jp: "原因となる", en: "cause", reading: "コーズ" },
  { id: 29, jp: "結果", en: "result", reading: "リザルト" },
  { id: 30, jp: "目的", en: "purpose", reading: "パーパス" },
  { id: 31, jp: "目標", en: "aim", reading: "エイム" },
  { id: 32, jp: "わかる", en: "find", reading: "ファインド" },
  { id: 33, jp: "発見する", en: "discover", reading: "ディスカバー" },
  { id: 34, jp: "気づく", en: "notice", reading: "ノーティス" },
  { id: 35, jp: "認識する", en: "realize", reading: "リアライズ" },
  { id: 36, jp: "気づいて", en: "aware", reading: "アウェア" },

  // 946 〜 955 相当 (image_85aa41.jpg)
  { id: 37, jp: "平均の", en: "average", reading: "アベレージ" },
  { id: 38, jp: "完全な", en: "complete", reading: "コンプリート" },
  { id: 39, jp: "正確に", en: "exactly", reading: "イグザクトリー" },
  { id: 40, jp: "ほとんど〜ない", en: "hardly", reading: "ハードリー" },
  { id: 41, jp: "自然", en: "nature", reading: "ネイチャー" },
  { id: 42, jp: "環境", en: "environment", reading: "エンバイロメント" },
  { id: 43, jp: "気候", en: "climate", reading: "クライメイト" },
  { id: 44, jp: "汚染", en: "pollution", reading: "ポルーション" },
  { id: 45, jp: "電気で動く", en: "electric", reading: "エレクトリック" },
  { id: 46, jp: "親しい", en: "close", reading: "クロース" },

  // 956 〜 972 相当 (image_85aa62.jpg)
  { id: 47, jp: "よく知られた", en: "familiar", reading: "ファミリア" },
  { id: 48, jp: "独立した", en: "independent", reading: "インディペンデント" },
  { id: 49, jp: "しだいである", en: "depend", reading: "ディペンド" },
  { id: 50, jp: "くつろぐ", en: "relax", reading: "リラックス" },
  { id: 51, jp: "尊敬する", en: "respect", reading: "リスペクト" },
  { id: 52, jp: "緊張して", en: "nervous", reading: "ナーバス" },
  { id: 53, jp: "注意", en: "attention", reading: "アテンション" },
  { id: 54, jp: "勇気", en: "courage", reading: "カレッジ" },
  { id: 55, jp: "安い", en: "cheap", reading: "チープ" },
  { id: 56, jp: "高価な", en: "expensive", reading: "イクスペンシブ" },
  { id: 57, jp: "価値がある", en: "worth", reading: "ワース" },
  { id: 58, jp: "産業", en: "industry", reading: "インダストリー" },
  { id: 59, jp: "話し合う", en: "discuss", reading: "ディスカス" },
  { id: 60, jp: "答える", en: "reply", reading: "リプライ" },
  { id: 61, jp: "主張する", en: "insist", reading: "インシスト" },
  { id: 62, jp: "不平を言う", en: "complain", reading: "コンプレイン" },
  { id: 63, jp: "話題", en: "subject", reading: "サブジェクト" }
];