import { WordPair } from './types';

export const WORD_LIST: WordPair[] = [
  // 796 〜 815 相当
  { id: 1, jp: "自然の", en: "natural", reading: "ナチュラル" },
  { id: 2, jp: "野生の", en: "wild", reading: "ワイルド" },
  { id: 3, jp: "天気", en: "weather", reading: "ウェザー" },
  { id: 4, jp: "リサイクルする", en: "recycle", reading: "リサイクル" },
  { id: 5, jp: "経験", en: "experience", reading: "イクスピアリエンス" },
  { id: 6, jp: "計画", en: "project", reading: "プロジェクト" },
  { id: 7, jp: "事故", en: "accident", reading: "アクシデント" },
  { id: 8, jp: "起こる", en: "occur", reading: "オカー" },
  { id: 9, jp: "準備する", en: "prepare", reading: "プリペア" },
  { id: 10, jp: "難題", en: "challenge", reading: "チャレンジ" },
  { id: 11, jp: "危険", en: "danger", reading: "デインジャー" },
  { id: 12, jp: "こうむる", en: "suffer", reading: "サファー" },
  { id: 13, jp: "解く", en: "solve", reading: "ソルブ" },
  { id: 14, jp: "規則", en: "rule", reading: "ルール" },
  { id: 15, jp: "状況", en: "situation", reading: "シチュエーション" },
  { id: 16, jp: "無駄", en: "waste", reading: "ウェイスト" },
  { id: 17, jp: "状態", en: "state", reading: "ステイト" },
  { id: 18, jp: "事柄", en: "matter", reading: "マター" },
  { id: 19, jp: "なる", en: "get", reading: "ゲット" },
  { id: 20, jp: "保つ", en: "keep", reading: "キープ" },

  // 816 〜 835 相当
  { id: 21, jp: "修理する", en: "repair", reading: "リペア" },
  { id: 22, jp: "開発する", en: "develop", reading: "ディベロップ" },
  { id: 23, jp: "描く", en: "draw", reading: "ドロー" },
  { id: 24, jp: "出版する", en: "publish", reading: "パブリッシュ" },
  { id: 25, jp: "賞", en: "prize", reading: "プライズ" },
  { id: 26, jp: "財宝", en: "treasure", reading: "トレジャー" },
  { id: 27, jp: "伝統", en: "tradition", reading: "トラディション" },
  { id: 28, jp: "創造する", en: "create", reading: "クリエイト" },
  { id: 29, jp: "生産する", en: "produce", reading: "プロデュース" },
  { id: 30, jp: "発明する", en: "invent", reading: "インベント" },
  { id: 31, jp: "破壊する", en: "destroy", reading: "デストロイ" },
  { id: 32, jp: "一部分", en: "part", reading: "パート" },
  { id: 33, jp: "1つ", en: "piece", reading: "ピース" },
  { id: 34, jp: "制度", en: "system", reading: "システム" },
  { id: 35, jp: "主な", en: "main", reading: "メイン" },
  { id: 36, jp: "全体の", en: "whole", reading: "ホール" },
  { id: 37, jp: "例えば", en: "for example", reading: "フォー イグザンプル" },
  { id: 38, jp: "実は", en: "in fact", reading: "イン ファクト" },
  { id: 39, jp: "〜に知られている", en: "be known to ~", reading: "ビー ノウン トゥー" },
  { id: 40, jp: "こわれる", en: "break down", reading: "ブレイク ダウン" },

  // 836 〜 855 相当
  { id: 41, jp: "急に始まる", en: "break out", reading: "ブレイク アウト" },
  { id: 42, jp: "引き起こす", en: "bring about", reading: "ブリング アバウト" },
  { id: 43, jp: "育てる", en: "bring up", reading: "ブリング アップ" },
  { id: 44, jp: "延期する", en: "put off", reading: "プット オフ" },
  { id: 45, jp: "中止する", en: "call off", reading: "コール オフ" },
  { id: 46, jp: "迷う", en: "get lost", reading: "ゲット ロスト" },
  { id: 47, jp: "克服する", en: "get over", reading: "ゲット オーバー" },
  { id: 48, jp: "苦しむ", en: "suffer from", reading: "サファー フロム" },
  { id: 49, jp: "指摘する", en: "point out", reading: "ポイント アウト" },
  { id: 50, jp: "参加する", en: "take part in", reading: "テイク パート イン" },
  { id: 51, jp: "いっぱいの", en: "full", reading: "フル" },
  { id: 52, jp: "からの", en: "empty", reading: "エンプティ" },
  { id: 53, jp: "いくつかの", en: "several", reading: "セブラル" },
  { id: 54, jp: "100万", en: "million", reading: "ミリオン" },
  { id: 55, jp: "好意的な", en: "friendly", reading: "フレンドリー" },
  { id: 56, jp: "礼儀正しい", en: "polite", reading: "ポライト" },
  { id: 57, jp: "かわいらしい", en: "pretty", reading: "プリティ" },
  { id: 58, jp: "深刻な", en: "serious", reading: "シリアス" },
  { id: 59, jp: "性格", en: "character", reading: "キャラクター" },
  { id: 60, jp: "理論", en: "theory", reading: "セオリー" },

  // 856 〜 875 相当
  { id: 61, jp: "研究", en: "research", reading: "リサーチ" },
  { id: 62, jp: "知能", en: "intelligence", reading: "インテリジェンス" },
  { id: 63, jp: "卒業する", en: "graduate", reading: "グラジュエイト" },
  { id: 64, jp: "選ぶ", en: "choose", reading: "チューズ" },
  { id: 65, jp: "しておく", en: "leave", reading: "リーブ" },
  { id: 66, jp: "守る", en: "protect", reading: "プロテクト" },
  { id: 67, jp: "結婚する", en: "marry", reading: "マリー" },
  { id: 68, jp: "ボランティア", en: "volunteer", reading: "ボランティア" },
  { id: 69, jp: "会話", en: "conversation", reading: "カンバセーション" },
  { id: 70, jp: "伝え合う", en: "communicate", reading: "コミュニケイト" },
  { id: 71, jp: "表す", en: "express", reading: "イクスプレス" },
  { id: 72, jp: "接する", en: "treat", reading: "トリート" },
  { id: 73, jp: "ついて行く", en: "follow", reading: "フォロー" },
  { id: 74, jp: "見えなくなる", en: "disappear", reading: "ディサピア" },
  { id: 75, jp: "到着する", en: "reach", reading: "リーチ" },
  { id: 76, jp: "戻る", en: "return", reading: "リターン" },
  { id: 77, jp: "〜の方へ", en: "toward", reading: "トゥワード" },
  { id: 78, jp: "説明する", en: "explain", reading: "イクスプレイン" },
  { id: 79, jp: "提案する", en: "suggest", reading: "サジェスト" },
  { id: 80, jp: "警告する", en: "warn", reading: "ウォーン" },

  // 876 〜 895 相当
  { id: 81, jp: "アドバイス", en: "advice", reading: "アドバイス" },
  { id: 82, jp: "さまざまな", en: "various", reading: "ベアリアス" },
  { id: 83, jp: "似ている", en: "similar", reading: "シミラー" },
  { id: 84, jp: "等しい", en: "equal", reading: "イークアル" },
  { id: 85, jp: "比較する", en: "compare", reading: "コンペア" },
  { id: 86, jp: "違い", en: "difference", reading: "ディファレンス" },
  { id: 87, jp: "偶然〜する", en: "happen to ~", reading: "ハプン トゥー" },
  { id: 88, jp: "連絡を取り合う", en: "keep in touch", reading: "キープ イン タッチ" },
  { id: 89, jp: "行われる", en: "take place", reading: "テイク プレイス" },
  { id: 90, jp: "途方に暮れて", en: "at a loss", reading: "アット ア ロス" },
  { id: 91, jp: "AとBの両方", en: "both A and B", reading: "ボウス エー アンド ビー" },
  { id: 92, jp: "AかBのどちらか", en: "either A or B", reading: "イーザー エー オア ビー" },
  { id: 93, jp: "偶然に", en: "by accident", reading: "バイ アクシデント" },
  { id: 94, jp: "誤って", en: "by mistake", reading: "バイ ミステイク" },
  { id: 95, jp: "減らす", en: "cut down on", reading: "カット ダウン オン" },
  { id: 96, jp: "今のところ", en: "so far", reading: "ソー ファー" },
  { id: 97, jp: "〜と何らかの関係がある", en: "have something to do with ~", reading: "ハブ サムシング トゥー ドゥー ウィズ" },
  { id: 98, jp: "〜について心配している", en: "be concerned about ~", reading: "ビー コンサーンド アバウト" },
  { id: 99, jp: "もし〜だったらどうしよう", en: "What if ~", reading: "ホワット イフ" },
  { id: 100, jp: "むしろ〜したい", en: "would rather ~", reading: "ウッド ラザー" }
];
